# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  filepicker_api_key: A18yHw06T6SM5gtllgMO5z
  secret_key_base: 709babe49c0b041eef023dca9cee297e9d2e83462bc617e34d4c7c777536bc0d8d219e318214c7f8490b418e06bc8673afaafe6f916bd7a30b2e258f85e82057

test:
  filepicker_api_key: A18yHw06T6SM5gtllgMO5z
  secret_key_base: 91fde916f9870ef0512dd3bd5cf0a15225415250ac738258c4ceb446929ff2198786656e6e02fe6aaf93764164896536d4ec640c1c6df968c06e3f71dca4d92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  filepicker_api_key: <%= ENV["FILEPICKER_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

